urbit/vere

pkg/noun/trace.c, pkg/noun/trace.h, pkg/vere/main.c, pkg/vere/vere.h
Resolves #104.
```console
$ bazel build :urbit
$ ./urbit -j zod
dojo> -time ~s2
dojo> |exit
$ cat zod/.urb/put/trace/0.json
```
[0.json](https://github.com/urbit/vere/files/10406450/0.txt)
=> Add functions to read static global variables in trace.c

.github/workflows/develop.yml, .github/workflows/master.yml, .github/workflows/release.yml
Resolves #106. Note that in addition to removing the `release` trigger, this PR also adds a `path` trigger to explicitly declare the paths CI jobs should run in response to changes to.
=> Remove use of release event in CI jobs

pkg/vere/io/term.c, pkg/vere/vere.h
The style of mouse reporting we want, "mouse clicks only", appears to not be supported in any common terminal emulator. Worse, in xterm, that mode ends up preventing the user from scrolling the buffer.
Until such a time where we can handle _all_ mouse inputs gracefully, we will refrain from taking mouse clicks in real terminals.
Closes #109. h/t @ashelkovnykov for spotting the xterm problem.
=> term: do not enable mouse reporting

.github/workflows/shared.yml, INSTALL.md, bazel/toolchain/BUILD.bazel
Resolves #113. As a side effect, this also disables the ability to cross compile from `linux-x86_64` to `linux-aarch64`. With this change, we no longer support any sort of cross compilation, although that support could be added back in the future should it become high enough priority.
Ran the following on an Arch Linux AArch64 VM:
```console
$ bazel test --build_tests_only ...
$ bazel build :urbit
$ ln -s bazel-bin/pkg/vere/urbit urbit
$ ./urbit -F zod -u https://bootstrap.urbit.org/urbit-v1.16.pill
<ctrl-d>
$ ./urbit zod
```
=> Enable native `linux-aarch64` build

pkg/vere/pier.c
As opposed to the color code for "bright black", which may cause legibility issues in dark color schemes.
Fixes #138.
=> term: make printfs render with 50% grayscale

INSTALL.md
I was confused when I tried to follow the instructions to build Vere and `bazel` didn't exist on my machine after running the "prerequisites" install command.
=> INSTALL.md: tell people to install bazel

INSTALL.md
I didn't realize I could just go ahead and run `bazel build :urbit` without first adapting one of the `bazel run //toolchain...` prerequisite commands first.
=> INSTALL.md: clarify macOS prerequisites

INSTALL.md
Remove the `$`s at the start of the paste commands. They don't provide any useful context here, since no output is shown, just the commands, and they make copy-pasting commands from the file to terminal more difficult.
=> install.md: remove paste command `$`s

pkg/vere/io/term.c
We were leveraging scrolling regions (the [`r` CSI command](https://terminalguide.namepad.de/seq/csi_sr/)) and scroll commands (the [`S` CSI command](https://terminalguide.namepad.de/seq/csi_cs/), for "scroll up") to create space in which printfs could exist. (This, besides the spinner, is where we depend on the assumption that there is a prompt on the bottom-most line of the screen.)
In the context of tmux, a scroll region scrolling up would simply push its contents up into scrollback/history. However, in the context of other terminals, 'S' is interpreted as "delete the top line(s), then shift all remaining content up". This obliterates the content of those top lines from existence irretrievably.
An alternative implementation prints a newline character at the bottom of the configured …
=> term: stop setting scroll regions for printfs

MAINTAINERS.md
To verify that the updated link formats are correct:
Run:
```
PLATFORM=linux-aarch64
PACE=edge
VERSION=`curl -s https://bootstrap.urbit.org/vere/$PACE/last | cat`
echo $VERSION  # see something similar to `1.18-7c890c3`
wget https://bootstrap.urbit.org/vere/$PACE/v$VERSION/vere-v$VERSION-$PLATFORM
```
Also, see [L155 of `.github/workflows/shared.yml`](https://github.com/urbit/vere/blob/c7107216dc1ff4824e314daca28ac64a2d83aabc/.github/workflows/shared.yml#L155):
```target="gs://${UPLOAD_BASE}/${{ inputs.pace }}/v${sha_version}/vere-v${sha_version}-${{ matrix.target }}"```
Resolves #179.
=> Add missing `{CS}-` segments to `edge` and `soon` link formats

.bazelrc, pkg/noun/allocate.c, pkg/noun/allocate.h, pkg/noun/trace.h
Resolves #140. Note that debug symbols are still not included in the exec configuration build despite `--host_copt='-g'` being set in [.bazelrc](https://github.com/urbit/vere/tree/0d7f0c636fa247ebc63dba63fff4c8c8bd5405cb/.bazelrc). It's unclear why this remains the case and may warrant further investigation if we deem it necessary.
Ran `bazel build --subcommands //pkg/vere:test-fake-ship` on both `linux-x86_64` and `macos-aarch64` machines and confirmed compiler invocations on both platforms included `-g -O3 -DU3_MEMORY_DEBUG -DU3_CPU_DEBUG`. The `linux-x86_64` build ran successfully, and the `macos-aarch64` build failed due to an existing issue (#40).
=> Run fake ship tests with optimized binary under memory and CPU debug

.bazelrc, INSTALL.md, bazel/third_party/aes_siv/aes_siv.BUILD, bazel/third_party/curl/curl.BUILD, bazel/third_party/ed25519/ed25519.BUILD, bazel/third_party/gmp/gmp.BUILD, bazel/third_party/h2o/h2o.BUILD, bazel/third_party/keccak_tiny/keccak_tiny.BUILD, bazel/third_party/openssl/openssl.BUILD, bazel/third_party/secp256k1/secp256k1.BUILD, bazel/third_party/sigsegv/sigsegv.BUILD, bazel/third_party/sse2neon/sse2neon.BUILD, bazel/third_party/uv/uv.BUILD, bazel/third_party/whereami/whereami.BUILD, bazel/third_party/zlib/zlib.BUILD
Resolves #83.
```console
$ bazel build :urbitdbg
```
When running the resulting binary under `gdb`, no arguments are optimized out, as expected with an optimization level of `-O0` (set by the debug configuration).
```console
$ gdb ./urbit
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation …
```
=> Add debug configuration to build system

pkg/noun/nock.c, pkg/noun/trace.c, pkg/noun/trace.h
Resolves #166 
I have added an support for the %meme hoon debugging hint. When a %meme hint is encountered, the usage of the vere memory arena is queried and printed (via slog).
The meme hint has two verbosity modes:
0: print the arena graph
1: print important memory information and the area graph
The arena graph is based on the ASCII graphs in Urbit's loom & road documentation
Example output in mode 0:
```
[=====$#############################################################################################~]
> ~>(%meme (add 1 1))
2
> =+  =+((bex (bex 30)) (bex (bex 30)))
=+  =+((bex (bex 30)) (bex (bex 30)))
>>  warning: loom sums under 99.99%
>   after bexing: [=====$------------%%%%%%%%%%%%%%%%%%%%%%%%%########################################################~]
~>(%meme.[0 leaf+"after …
```
=> Add support for the %meme debug hint to the vere runtime

bazel/third_party/gmp/gmp.BUILD
Resolves #176. A big thank you to @matthew-levan and @joemfb for uncovering this problem with the new `macos-aarch64` build and its resulting solution.
Both @matthew-levan and @tomholford confirmed this change allowed them to boot comets successfully on their respective `macos-aarch64` machines. Without the change, they were seeing a segfault.
=> Configure gmp with --disable-assembly on macos-aarch64

MAINTAINERS.md
As part of the release process, infrastructure ships should be updated, but that was not mentioned in the checklist.
=> MAINTAINERS.md: checklist to update infra ships

pkg/vere/king.c, pkg/vere/main.c, pkg/vere/pier.c, pkg/vere/vere.h
Resolves #157. As described in https://github.com/urbit/vere/issues/157#issuecomment-1409520195, this PR adds support for a `play` subcommand, which piggybacks off the existing replay implementation. This PR also augments the existing replay implementation with per-batch snapshots and a command line configurable batch size., which makes replaying large event logs a less painful experience for users. Snapshotting after each replay batch of course incurs a performance hit because we're writing to disk more frequently during replay, but replay is already slow, and in practice, users should not expect to see any difference. Additionally, this PR adds command line configurable replay batch size gives users a knob for increasing or decreasing the frequency with which snapshots are taken.
```
$ …
```
=> Implement simple replay command

.github/workflows/shared.yml
=> insert `live` into the `PACE` file during binary upload step

pkg/noun/vortex.c, pkg/noun/vortex.h, pkg/vere/main.c
I added the ability for the user pick two flags to pass to the eval subroutine. 
The first is the `--jam` flag. This takes the result from the inputted hoon code , `+jam`'s it and outputs it as a hexadecimal string. 
The second is the `--jamkhan` flag. This takes the result from the inputted hoon code, `+jam`'s it and outputs the noun wrapped in the proper `%khan` header (leading zero, noun size, noun) as binary data.
The proper use of the eval is as follows:
`echo "(add 2 2)" | vere eval --jamkhan > test.jam`
You can directly inject a `|meld` command to a running pier as follows:
`echo "[1 %urth %meld]" | ./vere  eval --jamkhan | nc -U ~/urbit/zod/.urb/conn.sock`
This should be the easiest way to `+jam` a noun for `%khan` use
This is a clone commit of …
=> Eval improvements

pkg/c3/defs.h, pkg/c3/motes.h, pkg/noun/events.c, pkg/noun/events.h, pkg/vere/db/lmdb.c, pkg/vere/db/lmdb.h, pkg/vere/disk.c, pkg/vere/main.c, pkg/vere/pier.c, pkg/vere/vere.h
`urbit chop <pier>` implements a simple, offline **event log truncation**[^1] tool.
`chop` gracefully stops the given pier (if running), backs up the current snapshot to `<pier>/.urb/bhk`, makes sure a current snapshot exists (i.e., is fully written to disk in `chk/*.bin` with no existing patch files), reads the metadata and the last event from the pier's event log, initializes a fresh event log in the `<pier>/.urb/log/chop` directory,  writes the metadata and last event from the original log into the fresh one, renames the original event log to `<pier>/.urb/log/chop/data_<first>_<last>.mdb.bak` where `first` and `last` are the first and last event numbers from the event log, and exits. 
Pilots are then free to move, archive, or delete their `.bak` event log file, resume normal operation …
=> chop: offline event log truncation

.github/workflows/shared.yml
This PR removes the ugly `grep`/`sed` command that was used to produce the `sha_version` variable we use for determining which URL to upload our binary to. Instead, we simply use the value written to `./bazel-bin/version` by `bazel build :version_str` (which would be, for example, `1.20` for the `live` pace, and `1.20-{SHORT-SHA}` for the other ones).
Resolves #219.
=> simplify upload binary ci code

docker/README.md, docker/start_urbit.sh
Modified start_urbit.sh script to allow the user to pick loom size and http port.
This is the start script Native Planet uses for our docker container
Resolves #189
=> Docker: Support for `--loom` and `--httpPort`

pkg/ent/ent.c
These were the most minimal set of changes that allowed me to build vere on macOS x86-64. See #131 for context. To build, I ran `bazel build --clang_version="12.0.0" :urbit`.
=> build: fix broken import for macos-x86_64

MAINTAINERS.md
=> Clarify release instructions

pkg/vere/main.c
-w and -F to continue with previous behavior of implicit pier creation.
Resolves #190
=> error when creating pier and -c unspecified. Exception: -w and -F

.github/workflows/shared.yml, docker/BUILD.bazel
Resolves #160
Adds a job which will push a tag with the pace value to DockerHub. Technically also adds a `live` tag which references the same image as the `latest` tag.
=> build: upload soon and edge tags to dockerhub

docker/BUILD.bazel
Resolves [builds failing when attempting to tag release with pace on DockerHub](https://github.com/urbit/vere/actions/runs/4298049619/jobs/7491731178).
Fixing issue introduced by #258.
@mcevoypeter @matthew-levan  Requesting urgent review, as this affects all builds and Docker uploads. I think this is the cause, but I'm unsure. I'm also unsure how to test this without going through a PR.
=> build: fix broken docker upload

pkg/noun/jets/a/add.c, pkg/noun/jets/a/dec.c, pkg/noun/jets/a/div.c, pkg/noun/jets/a/mod.c, pkg/noun/jets/a/mul.c, pkg/noun/jets/a/sub.c
Companion PR for [#6355](https://github.com/urbit/urbit/pull/6355) in `urbit/urbit` - **they must be released together**.
Required changes to `mod` jet to match bail condition of new `mod` logic in Arvo.
Tested changes successfully against latest code from `develop` (both `urbit/urbit` and `urbit/vere`).
=> jets: update mod jet to match Arvo changes

pkg/noun/events.c
Partially fixes #234.
This PR is a port of @joemfb's [urbit/urbit#6125](https://github.com/urbit/urbit/pull/6125).
Note that any stale `PROT_NONE` pages in live ship looms that currently exist will be cleaned out upon restart (i.e., when they upgrade to the new `vere`, at the least).
=> fix strange page errors by ensuring single guard page

pkg/vere/main.c, pkg/vere/pier.c
Partially Resolves #197
Adds the `--cue` option to the `eval` utility. This allows jammed nouns to be passed over `stdin` and pretty-printed to `stdout`.
Also includes a sub-option which will expect the incoming jammed noun to be Khan output. If the thread resulted in a `goof`, it's pretty-printed to `stderr` as a stack trace and the output is simply the `conn.c` header info (unique ID, `%avow` mark signalling Khan output, `%.n` loobean signalling thread failure).
Also includes the "todo"s from the comments for #155.
**Testing:**
- Built Vere in debug mode; no new warnings introduced
- Manually ran the following test cases in the terminal:
```
echo '42' | ~/Urbit/urbit eval -jn | ~/Urbit/urbit eval -cn
echo '[[1 2] [3 4]]' | ~/Urbit/urbit eval -jn | ~/Urbit/urbit eval -cn
echo "(cat 3 …
```
=> eval: add --cue option

docker/BUILD.bazel
Resolves [builds failing when attempting to tag release with pace on DockerHub](https://github.com/urbit/vere/actions/runs/4298049619/jobs/7491731178).
Can we please review this more carefully? I don't want this to be a repeat of #272. I'm also surprised that no one has commented on [every build on push to deploy failing for 10 days](https://github.com/urbit/vere/actions).
I genuinely don't know Bazel well. I'm attempting to implement the correct syntax using the existing files and Bazel docs as references, but I don't know that a PR is correct when I submit it, especially since it's impossible to test something like this locally.
=> build: fix docker pace deploy

pkg/vere/pier.c
Support for `zuse %414` and `lull %325`.
=> pier: decrement zuse/lull

bin/click, bin/click-format
Resolves #197 
**click** = **cli** for **c**onn.c & **K**han
I didn't know where it should live, so for now I put it into a `bin` folder in root Vere. Overview:
```
Usage:
click [options] <path-to-pier> <hoon> [<dependencies> ...]
click [options] -i <path-to-file> <path-to-pier> [<dependencies> ...]
click [-o|-p] -e -i <path-to-file> <path-to-pier>
Thin client for interacting with running Urbit ship via conn.c
options:
-e                  Execute jammed Hoon
-h                  Show usage info
-i <path-to-file>   Read input from file
-j                  Jam only
-k                  Execute command using "khan-eval" thread
-o <path-to-file>   Output to file
-p                  Filter failure stack traces from result and pretty-print them to stderr
-x                  Jam to hex
```
Where: …
=> click: thin client for interacting with a running ship from Earth

pkg/vere/io/http.c
The runtime component of the Eyre cache.
This is a draft as I still have a few open questions (and haven't tested anything yet, except confirming that this at least compiles...). Questions are in-line below.
=> http: add scry and noun caches

pkg/vere/king.c
Resolves #278 
I moved docking from `u3_king_done` to `_boothack_cb` to make sure ship is always docker by default.
There are some unknowns:
- Should it happen before or after `_king_doom`?
- I removed the "hack", as I believe `_boothack_cb` will only be called once. Is that okay?
=> Move auto-docking to the start of the boot process

docker/start_urbit.sh, pkg/vere/main.c, pkg/vere/save.c, pkg/vere/vere.h
This PR adds a command line option that allows the user to set the time in minutes between snapshots. This helps resolve the issues discussed in https://github.com/urbit/urbit/issues/4150. 
By allowing the user to set the time between shapshots it lets them decide how long they want to possibly wait to replay events. This also may allow urbit to run on an SD Card (which has ~10,000 write cycles.); reducing the cost to home host.
=> Command Line Option to set the time between snapshots

.github/workflows/develop.yml, .github/workflows/docker-once.yml, .github/workflows/docker-shared.yml, .github/workflows/master.yml, .github/workflows/next.yml, .github/workflows/release.yml, .github/workflows/shared.yml, docker/README.md
- Updates README (here and in DockerHub)
- Fixes bug that posted README updates to `tloncorp/urbit` instead of `tloncorp/vere`
- Moves DockerHub deploy tasks in build to separate workflow
- Adds a workflow which allows on-demand GitHub Action to redeploy Docker image to DockerHub
=> Updates to Docker build and README

pkg/vere/BUILD.bazel
Adds `--gc` to the boot phase of the fake ship tests as the binary we build for them already uses the correct `copts`.
Resolves #332.
=> ci: run fake ship tests under gc

.github/workflows/docker-shared.yml
Resolves failing GitHub build action
Tested [here](https://github.com/urbit/vere/actions/runs/4669925658/jobs/8269011549)
=> docker: use build cache; fix failing flow

pkg/vere/BUILD.bazel
=> ci: run `+vat %base` during boot and fake ship tests

pkg/noun/jets/e/json_de.c, pkg/noun/jets/k.h, pkg/noun/jets/tree.c
Note that this PR is attempting to merge to `next/kelvin/413`
- Address [this](https://github.com/urbit/vere/pull/342#discussion_r1163895177) comment
- Address [this](https://github.com/urbit/vere/pull/342#discussion_r1164477499) comment
- Consistent whitespace and indentation for `tree.c`
- Git is having trouble rendering it, but these are entirely whitespace changes
=> Minor additions to JSON jet PR

pkg/noun/serial.c
`develop` is currently broken, due to the intersection of #291 and #356. The fix is trivial.
=> u3: c3_assert -> u3_assert, missed in merge

.github/workflows/docker-shared.yml
Resolves [missing tags on DockerHub](https://hub.docker.com/r/tloncorp/vere/tags) (no issue exists for this, but multiple people have mentioned noticing it). This is also responsible for the missing `2.2` tag.
=> docker: fix all deployments tagged as 'once'

pkg/vere/io/http.c
This PR implements the `%cancel` effect from %eyre in the http i/o driver. It also properly handles request timeouts when we've already started sending a response (`u3_rsat_ripe`), and corrects handling of invalid effects.
These changes still need more testing. Advice on how to consistently induce %eyre to send %cancel effects would be appreciated.
/cc @pkova
=> http: implement request cancellation

pkg/vere/main.c
These were both mapping a full 8GB loom, preventing their use in limited environments.
=> vere: support --loom in grab and info commands

pkg/vere/io/ames.c
I broke the fine cache in #367, (specifically in a86724f12fcf79ac3048fd10452098834cda0bf1, refactoring the cache key refcounts).
=> ames: fix fine cache lookup

pkg/vere/io/ames.c
The length condition in `_fine_sift_meow()` did not account for the possibility of empty fragments.
=> ames: fixes meow min/max length calculation

pkg/vere/io/ames.c
Resolves memory leak on galaxies, where we leaked every packet that we're forwarding if we already know the lane.
=> ames.c: fix memory leak in _ames_try_send()

pkg/vere/io/http.c
Building on #391, this PR fixes a couple refcounting issues in http noun-cache functionality. It also adds request lifecycle tracking to ensure that timeouts are handled correctly.
=> http: track scry request lifecycle

.github/workflows/shared.yml
Resolves #44 and verifies the `bazel` binary we install on `linux-aarch64`.
=> ci: add uf self-hosted `linux-aarch64` and `macos-aarch64` runners

BUILD.bazel
Resolves #339. Depends on #409.
=> build: bump default `clang-macos-aarch64` version to `14.0.3`

.github/workflows/shared.yml
=> ci: `chown /usr/local` on our `linux-aarch64` runner

.github/workflows/shared.yml
=> ci: separate `chown` calls to fix buildjet jobs (`linux-aarch64`)

.bazelrc, pkg/noun/events.c
Resolves #427.
Disables snapshot validation by default, except for fake ship tests in CI.  To enable, run:
```
bazel build --config=snp_dbg :urbit
```
=> make U3_SNAPSHOT_VALIDATION a bazel build flag

pkg/noun/trace.h
Before this, the prototype for `u3t_trace_open()` had the wrong type.  Now Vere now builds cleanly without warnings.
=> events.h: fix u3t_trace_open() prototype to remove build warning

pkg/vere/io/ames.c
Fine requests entire 512-packet "pages" from arvo in each scry, and when it does that it marks the page as "pending" internally, so that if another request comes in for the same packet, it doesn't resend the scry, because it knows the scry is going to come back eventually.
This PR fixes a bug where instead of checking whether the page is pending, we checked whether the requested packet is pending.  This means that if requests for packets 1, 2, 3, ..., 512 all came in a row, we would fire off 512 scries, instead of only one.  Tlon has seen this issue in the wild when starting a large number of ships, while they're downloading their initial OTA from their sponsor.
This is a draft because it has not been tested yet.  I believe the bug can be reproduced by transferring a large file between …
=> ames: consolidate pending fine requests

pkg/noun/events.c, pkg/noun/events.h, pkg/noun/manage.c, pkg/noun/manage.h, pkg/noun/options.h, pkg/vere/lord.c, pkg/vere/main.c, pkg/vere/serf.c, pkg/vere/vere.h
Highly relevant to #410 (I think this behavior should be always-on in the presence of "swap"), but also likely useful as a standalone option for low-memory deployments. This is a draft PR as the behavior is hardcoded, not controlled by command-line arguments.
=> u3: "toss" ephemeral pages after every event

pkg/noun/jets/c/bex.c
In testing, I commonly use `=a (bex (bex 29))` as a way to use 128MB of memory.  It's been annoying that you can't do 256MB or more in this way, because the +bex jet didn't support it.  This PR raises that limit to strictly less than 2GB.  This also reduces the ephemeral memory usage of the `+bex` jet on large numbers by half.
This was limited to strictly less than 256MB because it used a gmp method to perform the binary exponent.  I briefly looked at whether gmp would handle double-length words for the exponent, but decided it was simpler and more efficient anyway to write this jet directly, ie allocate `a+1` bits and set the `a`th bit.  This saves one copy of the entire result, and allows it to function up to 2GB minus one.
This function would work correctly above this limit, but there …
=> jets: let +bex create atoms 256MB or more

pkg/noun/manage.c
These checks were introduced in v2.7, aborting the process if the snapshot metadata indicated that truncation had occurred. But the check as written is unnecessarily strict, and also aborts the process if the snapshot was larger than necessary. This PR prints a warning in that case and otherwise continues.
=> u3: improve snapshot corruption size checks

pkg/noun/events.c, pkg/noun/manage.c
... preventing spurious `loom: ward bogus` assertion failures. The guard page was being moved if necessary after initializing an inner road (accounting for road padding), but it could still be hit while initializing the road struct itself, in which case it would trigger an guard-page sanity assertion.
=> u3: move the guard page earlier when making roads

.github/workflows/shared.yml
It looks like this has been broken since the repository split. The version upload works, but the error check does not.
=> ci: fix error check in version upload

pkg/vere/pier.c
Old format: `/vere/~.2.10-9fac623`, new format `/vere/[once, live, soon, edge]/~.2.10-9fac623`.
=> pier: propagate pace to mars

pkg/vere/io/ames.c
=> ames: forward iff we're a galaxy

.bazelrc, BUILD.bazel, INSTALL.md, bazel/common_settings.bzl, bazel/toolchain/BUILD.bazel, pkg/c3/BUILD.bazel, pkg/ent/BUILD.bazel, pkg/noun/BUILD.bazel, pkg/ur/BUILD.bazel, pkg/urcrypt/BUILD.bazel, pkg/urcrypt/ge-additions/BUILD.bazel, pkg/vere/BUILD.bazel
Adds somewhere between 5-10% improvement to wall time.
I've ran all tests, booted several fakeships and comets with this installed, and all seems to work properly.
Mac x86 is coming, I just don't have access to an intel mac right now [but soon...].
Linux will come later once I figure out some bugs.
The following is time to boot a fakeship from a brass pill:
```
Without LTO:
________________________________________________________
Executed in  180.46 secs    fish           external
usr time   17.83 secs    0.10 millis   17.83 secs
sys time    0.23 secs    1.86 millis    0.23 secs
With LTO:
________________________________________________________
Executed in  164.87 secs    fish           external
usr time   15.65 secs    0.12 millis   15.65 secs
sys time    0.19 secs    1.94 millis    0.19 …
```
=> add -flto=thin to mac aarch64 build cflags for ez 10% gain

WORKSPACE.bazel
`zlib` 1.3 was [released on August 18, 2023](http://zlib.net/). Fixes recent CI failures as well.
=> build: upgrade `zlib` to v1.3

pkg/noun/serial.c
This PR ports urbit/urbit#5676, correcting an integer overflow in the +jam jet (leading to a mismatch on large-atom input). Fixes urbit/urbit#5674.
Releasing this fix is blocked on #346. DO NOT MERGE.
=> u3: rewrites jam atom encoding to maximize its range

.github/workflows/next.yml
The next/kelvin workflow uploads to docker edge. This shouldn't happen as it messes up edge testing if the next/kelvin branch isn't in sync with develop
=> Fixed next/kelvin workflow to not upload to docker

pkg/noun/vortex.c, pkg/vere/mars.c, pkg/vere/serf.c
... by always initializing from the ivory pill first.
=> vere: support stack traces on failing boot / full replay

pkg/noun/retrieve.c, pkg/noun/retrieve.h, pkg/noun/xtract.c, pkg/noun/xtract.h
This PR converts `u3r_cell()`/trel/&c inline functions and `u3x_cell()`/trel/&c to macros. This is mostly just a straightforward optimization of frequently used deconstructors, as prelude to optimizing all the jet-interface (`u3w*`) functions.
In the case of `u3x_atom()` the previously-defined macro repeated its argument, which is a bad pattern as that "argument" is often a call to another function. It has now been switched to an inline function.
=> u3: inline cell deconstruction

pkg/noun/jets/tree.c
This PR corrects a mistake from #291, introduced in porting from urbit/urbit#6008. Those new jets were declared for %140, but that PR was merged on top of the release of %139, and the declarations were not duplicated as they should've been.
=> u3: declares %139 jets for +scot and +scow

pkg/vere/io/ames.c
Some ships experience a lot of printfs like `ames: czar at zod.urbit.org: not found (b)` for galaxies that are up and have no problems with their DNS config. I initially thought this was something else, but the problem I found by mucking around with `tcpdump` is that we issue both a IPv4 A record query and a IPv6 AAAA record query. When the IPv6 query resolves it thrashes all kinds of state, sometimes causing the spurious printf above.
This PR configures `uv_getaddrinfo` to return just IPv4 addresses. I also removed the unnecessary while loop.
=> ames: resolve galaxy ips using ipv4 only

pkg/vere/db/lmdb.c, pkg/vere/db/lmdb.h, pkg/vere/disk.c
This PR resolves a bug that I introduced in #531. I added stronger validation during event log initialization by checking for the presence of metadata, but that was allocating on the loom (in the case of 32-bit or greater ships and/or lives). There are various chicken-and-egg problems with initializing old event logs for replay, so it seems best to just remove this whole operation from the loom.
=> vere: refactors event log metadata reading to avoid the loom

pkg/vere/disk.c
#547 was not quite enough to get `~binnec-dozzod-marzod` back online. This one is. Thanks to @mopfel-winrux for the solution.
=> disk: check for null pointer when writing through fak_o

pkg/vere/serf.c, pkg/vere/serf.h
This PR adjusts the serf's memory-pressure thresholds, adds state to track threshold events and avoid thrashing ("schmitt trigger"), and refactors post-event operation to use a bitmap and track operations more granularly.
These changes are useful on there own, and necessary for adding memory-pressure-based trimming to #508.
=> serf: adds new, stateful memory-pressure thresholds

pkg/vere/serf.c
This PR builds on #546, extending it's more-granular state management to the persistent memoization cache introduced in #508
=> serf: reclaim from persistent memoization cache

pkg/vere/io/ames.c
Vere side changes for the `%nail` PR https://github.com/urbit/urbit/pull/6828
=> ames: handle %nail gift, lanes to vere cache

pkg/noun/manage.c
... early migration prerelease
In other words, my comment at https://github.com/urbit/vere/pull/539#issuecomment-1806060851 was wrong, the couple of ships that are affected cannot just meld because the loom-sane assertion runs too early.
=> u3: adds unconditional freelist migration as workaround

WORKSPACE.bazel, pkg/noun/jets/b/mate.c, pkg/noun/jets/q.h, pkg/noun/jets/tree.c, pkg/noun/jets/w.h
These changes introduce a jet for the [`+mate` arm](https://developers.urbit.org/reference/hoon/stdlib/2a#mate), and were tested with the following commands:
```
> (mate ~ ~)
~
> (mate ~ `1)
[~ u=1]
> (mate `2 ~)
[~ u=2]
> (mate `3 `3)
[~ u=3]
> (mate `4 `5)
(error)
took ms/2.118
> ~>  %bout  (roll (gulf 1 1.000) |=([n=@ a=(unit @)] (mate (mate `n ~) (mate ~ `n))))
[~ 1.000]
> =hoon-mate |*([a=(unit) b=(unit)] ?~(b a ?~(a b ?.(=(u.a u.b) ~>(%mean.'mate' !!) a))))
took ms/4.603
> ~>  %bout  (roll (gulf 1 1.000) |=([n=@ a=(unit @)] (hoon-mate (hoon-mate `n ~) (hoon-mate ~ `n))))
[~ 1.000]
```
The `+mate` error text (`bail: fail` followed by stack trace) looks different from the `+need` error text (`dojo: hoon expression failed`) despite using the same jet error routine (i.e. …
=> jet `+mate` arm

pkg/noun/jets/f/fitz.c
With the recent discovery of a bug in `+fitz`, https://github.com/urbit/urbit/pull/6647, a jet mismatch was also uncovered. 
The `+fitz` jet erronously excludes all uppercase letters but the last one from the compatibility check.
```
> +fitz ['AB' 'CB']
%.n
> (fitz 'AB' 'CB')
%.y
> +fitz ['AC' 'CB']
%.n
> (fitz 'AC' 'CB')
%.y
```
Here the `+fitz` generator is the fixed Hoon version.
=> fixes +fitz jet mismatch

pkg/noun/v3/allocate.h, pkg/noun/v3/manage.c
The last minute migration change to #539 was just wrong. #551 is a functional workaround, but the change to the v3 migration itself also needs to be removed. We regret the error. (This can be fixed for real in v4 migration.)
=> u3: removes free-list ream from v3 migration

pkg/noun/imprison.c, pkg/vere/benchmarks.c
This PR ports urbit/urbit#6004. It is not urgent.
Benchmarking this against the old implementation would be worthwhile. It might also be worth inlining/decomposing `u3a_is_mutable()`; this is (currently) its only call-site, and the road pointer and seniority predicate cannot change throughout this loop.
=> u3: optimizes u3i_edit (nock opcode 10)

pkg/vere/io/lick.c
There is a bug in lick where if a port still has a connection and lick gets a %shut task the port can still send %soaks to arvo. Arvo poops when this happens. This bug also shows up when the port is disconnected and a %disconnect %soak is sent. This PR fixes both of these bugs
=> lick: Shut bug

pkg/vere/io/ames.c, pkg/vere/io/http.c
Also refactors fetching the protocol version twice.
=> ames, http: declare gang correctly when scrying

pkg/noun/jets/c/swp.c
Previously running `(swp 3)` on a 70MB atom would always exhaust a 2gb loom. With this we can easily `(swp 3)` and even `(swp 0)` a 500MB atom. Note that fares a lot better even with no special casing of blocksizes 0, 3 and 5.
=> jets: make a real jet for swp

pkg/vere/io/ames.c, pkg/vere/mdns.c, pkg/vere/mdns.h
Also print a better error message for linux users if avahi is not installed.
I'm targeting this wonky branch to get this into 3.0.
=> mdns: distinguish fake ships in the mdns namespace

BUILD.bazel
Reverts urbit/vere#579
We have to revert this until @jalehman gets back and we can access macstadium. CI on develop is broken otherwise. No biggie, we'll just put this back after.
=> Revert "build: recent macOS updates clang"

WORKSPACE.bazel
Looks https://zlib.net immediately stops distributing the old version the very instant a minor version bump happens. This broke our CI.
=> bazel: bump zlib

WORKSPACE.bazel
1.1.1t is 404ing on openssl.org.
Resolves #
=> build: bump openssl dep

pkg/noun/events.c, pkg/noun/version.h, pkg/vere/disk.c, pkg/vere/main.c, pkg/vere/mars.c, pkg/vere/pier.c, pkg/vere/vere.h
Refactors the epoch system migration to prevent downgrade shenanigans and jankery when pilots booted 3 -> 2 -> 3, or other similar permutations. We use the version number in the `META` database of `log/data.mdb` as our migration indicator now instead of the (non-)existence of `log/data.mdb`.
=> fix epoch migration bug

pkg/vere/disk.c
- event log metadata was serialized through loom-dependant apis. this could cause crashes in certain scenarios of partial-initialization.
- the pre-release "repair" on disk initialization handled missing but not empty  top-level lmdb environments. these can be created by crashes during the repair, so it's best to handle them as well.
=> epoc: fix log metadata write bug, make pre-release repair more robust

pkg/vere/disk.c
This fixes a null-pointer write in epoc list function, introduced as part of a separate fix in #592.
=> vere: fix chop

pkg/vere/disk.c, pkg/vere/main.c, pkg/vere/mars.c, pkg/vere/vere.h
This PR changes the chop command, removing log rollover so as to be effective even when (nearly) out of disk space. It also includes refactoring of the epoc lifecycle operations to centralize the enforcement of their invariants, and improves error handling throughout.
=> vere: fix epoc lifecycle error handling, enforce invariants

pkg/vere/io/http.c
Resolves #604
The root of the issue here is that `sax_p` and `nax_p` contain the same noun. The value from `sax_p` later becomes the key for `nax_p`. When we later free both maps in `_http_io_exit` we end up with a double free.
=> http: do not double free scry cache path

pkg/noun/v3/manage.c
Some ships migrating to vere-v3.0 experienced "loom: corrupt" when reclaiming the bytecode caches when running the v3 migration. This PR does fix the issue, but it may or may not be exactly right. @joemfb will have to take a look.
=> v3-migrate: ream before reclaiming bytecode caches

pkg/noun/hashtable.c, pkg/noun/hashtable.h, pkg/noun/jets.c, pkg/noun/jets.h, pkg/noun/manage.c, pkg/noun/nock.c, pkg/noun/nock.h, pkg/noun/zave.c, pkg/noun/zave.h
Reverts urbit/vere#538
My ship ran into a refcounting bug during pre-release testing of vere-v3.0. The only part of the release that touches the relevant codepath is this PR, so we have decided to revert it.
=> Revert "u3: restore old-style, efficient reap to u3m_love()"

pkg/noun/manage.c, pkg/vere/main.c
... to support repairing errant refcounts interfering with the boot process.
=> vere: adds --gc-early flag to pack and meld subcommands

pkg/vere/io/http.c
If the cache entry for any given url was cleared, this would be indicated by a null entry for that url, and vere would serve a 404 for those cases, instead of falling back to the normal, dynamic behavior of injecting the request into eyre.
Here, we make eyre serve from the cache only if there is a full cache entry for the url, and have it proceed into normal request injection logic otherwise.
This way, setting a cached response for some url no longer means giving up dynamic responses on that url for the rest of time.
Recent versions of eyre exhibit the same behavior. As such, in practice, this code won't change the observed behavior without a similarly-patched version of eyre. For that, see the sister PR, urbit/urbit#6909.
The bulk of the updated logic in `_http_cache_respond()` comes …
=> http: dynamic responses for empty cache entries

flake.lock
This updates nixpkgs in `flake.lock` to bring in a fix for the `FHSUserEnv` required to run Bazel on NixOS. Without this fix, on recent NixOS, an improper LD_LIBRARY_PATH will be set, causing glibc to crash processes with "stack smashing detected."
See NixOS/nixpkgs#263201
=> nix: update flake.lock to fix FHSUserEnv

pkg/vere/BUILD.bazel, pkg/vere/ames_tests.c, pkg/vere/io/ames.c, pkg/vere/mdns.c
While debugging urbit/urbit#6936, we discovered that the STUN client implementation is incorrectly parsing ip/port pairs from responses. This has no effect on the behavior of informal pinging as written, which is only using the responses to detect changes in network topology. But we may want to use those values at some point, so it's best to correct them sooner rather than later.
This PR includes tests, and some minor refactoring of the STUN protocol implementations to facilitate testing.
=> stun: corrects response decoding, adds tests

INSTALL.md, bazel/common_settings.bzl, pkg/vere/BUILD.bazel, pkg/vere/main.c, pkg/vere/platform/darwin/mach.c, pkg/vere/vere.h
Debugging vere on macOS is quite something because as soon as we get a single SIGSEGV lldb enters an infinite loop. The cause of that is a lldb bug and the root cause of that is a macos kernel bug. Here we implement the same workaround that Go does to make the debugger work.
https://bugs.llvm.org/show_bug.cgi?id=22868#c1
=> macos: fix lldb

WORKSPACE.bazel, bazel/third_party/natpmp/natpmp.BUILD, pkg/vere/BUILD.bazel, pkg/vere/io/ames.c
Same as https://github.com/urbit/urbit/pull/3261 but for vere. From what I can tell this NAT-PMP stuff is fairly well supported by routers, works on my machine at least.
=> ames: add libnatpmp for automatic port forwarding

pkg/vere/disk.c
=> add more helpful chop message

pkg/vere/disk.c
#635 broke the develop branch and therefore broke CI on `urbit/urbit`. It's a real C moment that CI failed to catch this one.
=> disk: fix broken chop error message

pkg/vere/disk.c
Reverts urbit/vere#642
There's something very mysterious going on, `urbit/urbit` CI segfaults but `urbit/vere` does not.
=> Revert "disk: fix broken chop error message"

pkg/vere/main.c
CTRL+z to force kill an urbit process has been broken for some time. This was caused by our SIGTSTP handler being overwritten in `_cw_play_imp` that gets called not only during replay but on every boot if we're not a new pier.
=> main: restore SIGTSTP handler after replay

pkg/vere/disk.c, pkg/vere/main.c, pkg/vere/vere.h
Adds `--lmdb-map-size` to specify LMDB's initial memory mapping size, intended for use by users who need a size smaller than our default of 500G. Note: `case 12` to avoid collision with the other arg added in #654.
=> disk: parameterize lmdb map size

pkg/noun/nock.c
Solves #660 
Prevents Nock 9 from crashing the pier if the axis argument is a cell. Without the check Vere may call `u3qc_cap` on a cell, leading to a segfault or an assertion failure:
```
Assertion '_(u3a_is_atom(b))' failed in pkg/noun/retrieve.c:1011
```
To reproduce the bug, run in Dojo:
```
.*(0 [9 [2 2] 0 1])
```
Is there a way to add a unit test to guard against a downgrade?
=> fix nock 9 crashing pier if axis is cell

WORKSPACE.bazel, bazel/third_party/natpmp/natpmp.BUILD, pkg/vere/BUILD.bazel, pkg/vere/io/ames.c
This is #593 that got reverted in #644 because it broke `urbit/urbit` CI. This PR fixes the issue which was unconditionally calling `uv_poll_init` on a socket that was initialized with `initnatpmp` without checking if `initnatpmp` returned an error first.
=> ames: libnatpmp for real this time

pkg/noun/BUILD.bazel, pkg/noun/jets/e/crc32.c, pkg/noun/jets/tree.c, pkg/noun/jets/w.h
Adds crc32 jet. This will be used to validate uncompressed gzip data.
https://github.com/urbit/urbit/pull/6997
=> Add crc32 jet

pkg/vere/king.c, pkg/vere/main.c
This PR fixes an issue introduced in #654, whereby docked binaries could not replay.
=> vere: support .run in subprocess replay

pkg/c3/defs.c, pkg/c3/defs.h, pkg/vere/BUILD.bazel, pkg/vere/ames_tests.c, pkg/vere/io/ames.c, pkg/vere/io/ames/stun.c, pkg/vere/io/ames/stun.h
This PR factors out a couple small modules from ames, in anticipation of merging in the directed messaging driver. Built on top of (and targeting) #639.
=> ames: factor out stun implementation and basic de/serialization functions

INSTALL.md, bazel/third_party/avahi/avahi.BUILD, flake.lock, flake.nix
Resolves #628
I would need someone on normal linux and mac to double check, if the avahi `--with-distro=none` does not break builds. [nixpkgs sets this](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/libraries/avahi/default.nix#L169), however, because avahi's configure does not support detecting nixos, or falling back to "none".
=> nix: fix vere compilation

pkg/noun/events.c
@Fang- discovered this longstanding problem of overeager snapshot validation preventing crash recovery.
=> u3: better recovery from crashes during snapshot patch application

.gitignore
I can't think of a reason `MODULE.bazel` and `MODULE.bazel.lock`, both of which are auto-generated, shouldn't be in the `.gitignore` file.  I keep manually ignoring them.
=> gitignore MODULE.bazel and lock

pkg/vere/disk.c
=> disk: update epoc.txt and vere.txt atomically

pkg/vere/main.c
=> play: use `libuv` for replay

pkg/vere/io/ames/stun.c
Informal pinging has been broken since #623, luckily this was unreleased, but existed edge.
=> stun: fix stun

pkg/vere/io/mesa.c, pkg/vere/io/mesa/pact.c
=> mesa: misc. bugfixes

pkg/vere/io/lick.c
Fixes a bug where you couldn't access any lick ports after opening the first one due to stupid pointer allocations
=> Lick Pointer bug

pkg/noun/events.c
This is another one of the address sanitizer catches.
For whatever reason my directed messaging fakeship ended up in a situation with empty `control.bin` and `memory.bin`. When starting up this fakeship the address sanitizer blows up here:
https://github.com/urbit/vere/blob/f5799a9e778d3e479f1e81ab0b33a4da2807218b/pkg/noun/events.c#L459-L467
`len_w` is 0, `malloc(0)` is implementation defined but does give a non-null pointer on macos, which means that on line 462 we are reading random garbage.
=> events: do not read garbage memory on empty control files

WORKSPACE.bazel, pkg/noun/jets/e/chacha.c, pkg/noun/jets/tree.c, pkg/noun/jets/w.h
See https://github.com/urbit/urbit/pull/6932 and https://github.com/urbit/urcrypt/pull/11
=> ChaCha jets

pkg/c3/defs.h, pkg/noun/hashtable.c, pkg/noun/jets/c/clz.c, pkg/noun/jets/c/ctz.c, pkg/noun/jets/c/ham.c, pkg/noun/jets/c/hew.c, pkg/noun/jets/c/rig.c, pkg/noun/jets/q.h, pkg/noun/jets/tree.c, pkg/noun/jets/w.h
Adds jets for the operations in urbit/urbit#6961, to support urbit/urbit#6932.
=> jets: for new atom ops

pkg/noun/jets/g/plot.c, pkg/noun/jets/q.h, pkg/noun/jets/tree.c, pkg/noun/jets/w.h
This PR jets urbit/urbit#6963. Opened as a draft as it is missing some overflow checking and optimization. Needed by urbit/urbit#6932.
=> jets: adds $plot (+fax and +mes)

INSTALL.md, build.zig, build.zig.zon, ext/curl/build.zig.zon, ext/h2o/build.zig.zon, ext/openssl/build.zig.zon, ext/urcrypt/build.zig.zon, pkg/c3/build.zig, pkg/c3/build.zig.zon, pkg/ent/build.zig, pkg/noun/build.zig, pkg/noun/build.zig.zon, pkg/ur/build.zig, pkg/ur/build.zig.zon, pkg/vere/build.zig, pkg/vere/build.zig.zon
This refactor decouples the build phases of the Vere submodules (c3, ent, ur, noun, and vere) from the main Urbit binary Zig build by moving them into separate Zig builds within each respective pkg directory.
This change is intended to resolve certain Zig cache issues where the linker fails to locate newly added symbols in submodules when these symbols are used in dependent modules.
=> build: refactor and decouple pkg builds from main build

pkg/vere/king.c, pkg/vere/main.c
When testing 410 with vere-v3.2 I've repeatedly ran into an issue where my ship turns off every few days. This was caused by the king receiving a `SIGPIPE`, something we ostensibly are ignoring with `sigaction`, [however](https://www.linuxjournal.com/article/2121):
```
In a multi-threaded application, there is always the question of which thread the signal will actually 
be delivered to. Or does it get delivered to all the threads? [...]
If it is an asynchronous signal, it could go to any of the threads that haven't masked out 
that signal using sigprocmask().
```
Our "multi-threaded" application is the libuv thread pool. Using `pthread_sigmask` fixes the issue since all child threads inherit the signal mask.
=> main: really ignore SIGPIPE

pkg/vere/ivory/ivory.sh
Needed for 410 because of the keyfile changes with the added rift.
=> misc: update ivory pill

pkg/vere/serf.c
#749 introduced an issue where CI on urbit/urbit suddenly became dog slow. This was eventually traced down to the fact that jets registered by the ivory pill in the serf were extremely slow to check for because of missing structural sharing. The only reason to install the ivory pill in the serf is to have stacktraces when arvo fails to compile in CI. Removing that feature is acceptable to keep things moving for now.
=> serf: do not install ivory pill for now

pkg/vere/io/mesa.c
Blocking scries would never resolve since we were never updating the CTAG_WAIT entry to CTAG_BLOCK
=> mesa: don't free pict before hamt get

pkg/vere/king.c
We're not following redirects anyways so this is pretty weird. Surfaced by ships running 410 and trying to curl the galaxies running 411 for double boot protection, getting a redirect to the galaxy login screen and then retrying five times.
=> king: do not retry on http 3xx in king_curl_bytes

pkg/vere/io/ames.c, pkg/vere/io/mesa.c
A beautiful idea but given that the receive buffer sometimes ends up as the sender buffer in `ames.c` and that `uv_udp_try_send` fails a lot with dead flow consolidation turned on we have to revert this.
=> ames, mesa: revert static receive buffer allocation

build.zig, ext/libuv/build.zig, ext/libuv/build.zig.zon, ext/murmur3/build.zig, ext/urcrypt/build.zig, pkg/vere/arena.h, pkg/vere/build.zig, pkg/vere/io/ames.c, pkg/vere/io/lss.c, pkg/vere/io/lss.h, pkg/vere/io/mesa.c, pkg/vere/io/mesa/bitset.c, pkg/vere/io/mesa/bitset.h, pkg/vere/io/mesa/mesa.h, pkg/vere/io/mesa/pact.c, pkg/vere/vere.h, pkg/vere/verstable.h
This PR contains several big improvements to the mesa driver:
* We don't allocate nouns all over the place anymore.
* To enable the previous we don't use our HAMT anymore, instead we use a [off-the-shelf hashtable](https://github.com/JacksonAllan/Verstable).
* We don't do individual `malloc` and `free` calls all over the place anymore. The allocations have been grouped into lifetimes each with their own memory arena.
* We don't allocate at all when we don't need to.
As a result we go from around 15 megabytes/second to 190 megabytes/second bandwidth for localhost peeking on my macbook M2. Corresponding speeds between two terrible 1 cpu 2gb VM:s situated on the other sides of the Atlantic go from around 2 megabytes/s to 18 megabytes/s.
There is still room to optimize the speed of directed …
=> mesa: improvements

pkg/vere/io/mesa.c
The galaxy was no-oping when hearing forwarded pages since we were checking for our own active requests before looking in the pit
=> mesa: move forwarding page before checking request

.github/workflows/docker-shared.yml, .github/workflows/shared.yml, .gitignore, INSTALL.md, build.zig, build.zig.zon, ext/avahi/build.zig, ext/backtrace/build.zig, ext/curl/build.zig, ext/h2o/build.zig, ext/openssl/build.zig, ext/sigsegv/build.zig, pkg/c3/build.zig, pkg/noun/build.zig, pkg/vere/build.zig
Support for `zig-0.14.0`. Also supports the ability to use `zig build -fcompdb` to generate `compile_commands.json` (for `clangd` integration), given you [compile](https://github.com/ziglang/zig?tab=readme-ov-file#building-from-source) a Zig compiler from [452253e](https://github.com/matthew-levan/zig/commit/452253e9bff6cf726e8bf8eb8a09190b44bf3798). I used the following build commands on my `macos-aarch64` machine, though yours may vary:
```
cmake .. -DZIG_STATIC_LLVM=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSROOT=$(xcrun --show-sdk-path) -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@19/bin/clang++ -DCMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/lib -lzstd"
make -j$(sysctl -n hw.ncpu)
```
I will continue updating this PR to maintain compatibility with upstream changes and intend on opening this …
=> build: update for zig v0.14.0

pkg/vere/main.c
Resolves #679. Read this [comment](https://github.com/urbit/vere/issues/679#issuecomment-2706929997) for a summary of the underlying issue.
This PR adds the `--watch-replay` flag to the `play` subcommand. 
When `--watch-replay` is passed to `play`, a watcher thread is spawned to ensure process orphaning does not occur. This option is only helpful when replaying events during normal pier startup, where we spawn a child process, so it's off by default. When we start a pier normally (i.e., without the `play` subcommand), we turn it on in `_cw_play_fork`. 
Keeping `--watch-replay` off by default _prevents_ operators that run `play` with no `STDIN` from experiencing issue #679, like so:
```
matt@mbp14 vere % ./urbit play zod < /dev/null
play: god save the king! committing sudoku...
```
No …
=> play: add `--watch-replay` flag

pkg/vere/io/ames.c
This looks for ships in both .peers and .chums, to account for migrated ships
(see: https://github.com/urbit/urbit/blob/develop/pkg/arvo/sys/vane/ames.hoon#L10661-L10700)
=> ames: scry for lanes using /chums/[ship]/lanes

pkg/vere/io/ames.c
A few issues were discovered when I (~dinleb-rambep) migrated ~norsyr-torryn to directed messaging yesterday. One issue is that if a galaxy has been migrated but a peer has not, then ames-to-ames forwarding would not work. The reverted PR was meant to mitigate this, but the types from the ames and mesa lane scries are incompatible. We will address this with an arvo PR instead.
=> Revert "ames: scry for lanes using /chums/[ship]/lanes"

pkg/vere/verstable.h
Previously we were running into a case where where Verstable calls the value destructor before rehashing a key. This key was allocated on the same arena as the value which lead to a use-after-free.
=> verstable: always run value destructors after key destructors

pkg/vere/io/mesa.c, pkg/vere/king.c, pkg/vere/pier.c, pkg/vere/vere.h
One fix related to double boot protection, another small mesa bug. See the commit messages for details.
=> misc: fixes for vere-v3.2

pkg/vere/io/http.c
fixes a bug where a POST request to /foo/bar would return the cached response for a GET at /foo/bar
=> http: only check cache on GET requests

pkg/vere/auto.c
Each driver in the king has an event queue. When new events are about to be handled, these queues get pulled from in a specific order. We do this so that a ship that receives a ton of ames packets doesn't block handling terminal keystrokes or web interface HTTP requests.
`vere-v3.2` added the `mesa.c` driver for Directed Messaging. The driver was incorrectly put at the very bottom of `auto.c` which means the highest priority driver. This combined with the proliferation of "dead" permanent networking flows caused some ships to appear less responsive when compared to `vere-v3.1`.
=> auto: fix driver priority

pkg/vere/mars.c
I removed the ivory pill from the serf in #750, but I missed this code path in _mars_do_boot. This code only ever runs if the process has been killed during initial boot and we have to replay. The older ivory pill being installed breaks the structural sharing for jet registrations, causing ships that crash during boot to perform extremely poorly until they get melded.
=> mars: really don't install the ivory pill in the serf

pkg/noun/jets/c/bex.c, pkg/ur/bitstream.c, pkg/vere/db/lmdb.c
These issues came up while testing #812 under Asan and Ubsan. The +bex jet had already been partially fixed in #764. There are many more of these undefined left shifts in the codebase. Those should be systematically rectified, maybe as part of #794.
=> vere: fix some undefined behavior

pkg/noun/jets.c, pkg/noun/nock.c
`u3k()` / `u3a_gain()` asserts that a noun reference is not `u3_none`, while `u3z()` / `u3a_lose()` does not. Neither needs -- they will both safely no-op given `u3_none` (due to the `..._is_normal()` conditions inside their implementation functions). The inconsistency here makes for inconsistent code -- the presence of `u3z(u3_none)` may indicate misconceived refcount handling.
This PR does not resolve the overall issue. It just corrects a couple cases by removing unneeded refcount operations and notes another.
=> u3: remove unnecessary refcount operations (losing u3_none)

pkg/noun/nock.c
Currently, if Nock bytecode interpreter executes an autocons and does not need the subject to be left on top of the stack (e.g. tail position), it would delay losing it after running both the head and the tail formulas, and only lose them when consing the results. 
This PR reduces the memory usage by allowing the tail formula to consume the subject if it is not needed, losing it sooner.
=> nock: lose subject in autocons more eagerly

pkg/noun/events.c, pkg/noun/events.h, pkg/noun/hashtable.c, pkg/noun/manage.c, pkg/noun/version.h, pkg/noun/vortex.h
This PR is based on and targets #812. It also includes a copy of #825, as that fix is necessary for the relocated home road to not interfere with inner-road promotion. It implements "option 2" from https://github.com/urbit/vere/issues/451#issuecomment-1591719816.
Moving the home road makes sense given #812, as it requires that the entire first page be reserved from the heap. Once the road home is moved, there's no reason for the snapshot to consist of two separage memory-image segments, as only the bottom of the loom needs to be preserved. This simplifies the snapshot system by removing much of the complicated, direction-switching redundancy in its implementation, and simplifies the handling of snapshots themselves as they are now a single file.
Since these changes require a …
=> u3: moves home road to loom start, simplifies snapshot system

pkg/noun/hashtable.c
This PR fixes a longstanding bug in hashtable road promotion, wherein null slots in table root struct would dereferenced as posts and reallocated, causing unnecessary "traversal" and extra, unused memory allocation.
=> u3: skip null slots in u3h_take() and friends

.github/workflows/shared.yml, build.zig, pkg/noun/allocate.c, pkg/noun/allocate.h, pkg/noun/equality_tests.c, pkg/noun/retrieve.c
These changes were developed on top of #812, as part of a(nother) failed effort to develop leak-free unification of senior memory. But they stand alone, and deserve separate review.
This PR fixes a bug wherein deeper addresses were not preferred when unifying two nouns on the same road. It also optimizes the unification implementation by using separate functions for normal and senior unification and removing branches. Finally, it enables home-road unification when the current road is the home road and there are no child roads, and adds basic unit tests for these scenarios.
=> u3: refactor unifying equality

pkg/noun/nock.c
Reverts urbit/vere#827
This PR causes an instant segfault in the serf after upgrading on `~dinleb-rambep`, `~norsyr-torryn` and probably all pre-existing ships. The segfault has the following stacktrace:
```
urbit 3.4-0969b6de10
boot: home is /root/dinleb-rambep
disk: loaded epoch 0i575532513
loom: mapped 2048MB
boot: protected loom
live: mapped: GB/1.945.878.528
live: loaded: KB/16.384
boot: installed 1362 jets
loom: image backup complete
disk: created epoch 575532513
loom: mapped 2048MB
lite: arvo formula 4ce68411
lite: core 641296f
lite: final state 641296f
disk: loaded epoch 0i575532513
loom: mapped 2048MB
boot: protected loom
live: mapped: GB/1.945.878.528
live: loaded: KB/16.384
boot: installed 1362 jets
vere: checking version compatibility
loom: external fault: 0 (0x200000000 : …
```
=> Revert "nock: lose subject in autocons more eagerly"

pkg/vere/dawn.c
Added Check of +.feed to make sure its a cell, if its a cell and a moon we crash before running
`+veri:dawn`
Resolves #818
=> Better error message for bad moon keys

pkg/noun/build.zig, pkg/noun/jets/136/tree.c, pkg/noun/jets/e/adler.c, pkg/noun/jets/e/crc.c, pkg/noun/jets/w.h
This PR implements jets for newly introduced `+checksum` core in `zuse.hoon` in #7058.
=> +checksum jets for zuse.hoon

pkg/noun/nock.c
I realized that branch elimination introduced in #850 led to crashes like in this example:
```
.*(0 [%6 [%5 [%0 1] %1 0] [%1 42] [%6 [%1 %0] [%0 0 0] [%1 42]]])
```
When outer %6 is compiled, `_n_formulaic` checks the validity of formulas in branches, replacing them with single `BAIL` instruction if the formula is malformed, which would make it always crash. From POV of _n_formulaic inner %6 is valid, since the condition expression and at least one of the branch expressions are valid. But when inner %6 is compiled, we only compile the invalid branch due to branch elimination, leading to a crash.
For that reason _n_formulaic has to be more strict in the presence of branch elimination.
=> branch elimination in _n_formulaic

pkg/noun/jets/tree.c
There was a jet mismatch between `+muk` definition in hoon.hoon and the jetting function that was fixed in [dcb4231@urbit](https://github.com/urbit/urbit/commit/dcb42318131d83a08cdd03e44fb7cb692cf93608). Same fix could not be applied in /lib/tiny.hoon due to logistical complexities. However, the library and the naive rollup contract do not call `+muk` directly, and the mismatch is not directly observable, since it involves passing the length of the key that exceeds its size measured with `+met`, and `+muk` callers `+mug` and `+mum` don't do that. So it would suffice to just remove the registration from `%a50` root.
=> jets: remove +muk registration from /lib/tiny

pkg/noun/manage.c
#875 added a mechanism to make bytecode revisions easier to ship, but that mechanism was invoked too early.
=> u3: moves "stale bytecode" migration to later in init process
