.github/workflows/shared.yml

Correct name of Docker README for Docker image upload in CI

---

.github/workflows/shared.yml
bazel/toolchain/BUILD.bazel

Resolves #148. Note this introduces a temporary fix that will be addressed via #151.

Explicitly install `clang` with `brew` in `macos-x86_64` CI

---

bazel/third_party/curl/curl.BUILD
bazel/third_party/gmp/gmp.BUILD
bazel/third_party/h2o/h2o.BUILD
bazel/third_party/openssl/openssl.BUILD
bazel/third_party/uv/uv.BUILD
pkg/c3/portable.h
pkg/noun/manage.c
pkg/vere/db/lmdb.c
pkg/vere/disk.c
pkg/vere/king.c
pkg/vere/lord.c
pkg/vere/main.c
pkg/vere/time.c
pkg/vere/vere.h

Resolves #153. For the rationale behind this PR, see #153.
Ran the following on `linux-x86_64` and `macos-aarch64`:
```console
$ bazel build :urbit
$ ./urbit -F zod -B path/to/solid.pill
$ zod/.run
```
Note `path/to/solid.pill` pointed to a local checkout of commit `ef2a0c913b66a04adda7bf1213ca61ef5c0a68e6` in https://github.com/urbit/urbit.

Remove Windows-specific code

---

.github/workflows/master.yml
.github/workflows/shared.yml

disable fakeship tests on jobs triggered by pushes to master

---

CONTRIBUTING.md

vere no longer squashes

---

.github/workflows/shared.yml

remove `1.16`-specific CI code

---

pkg/vere/pier.c

fix -Y filename

---

.github/workflows/shared.yml

CI: add `-v` and `*-musl` to the `chown` path

---

INSTALL.md
pkg/vere/main.c

Strip trailing commit SHA from version number when downloading pill

---

.github/workflows/shared.yml

CI: add `GH_TOKEN`

---

docker/README.md

_Ask yourself whether the dream of heaven and greatness should be waiting for us in our graves — or whether it should be ours here and now and on this earth._

path correction: tloncorp/urbit ➞ tloncorp/vere

---

BUILD.bazel

ci: export `PACE` file for docker build usage

---

CONTRIBUTING.md

CONTRIBUTING.md: no one other than PR authors should merge generally

---

WORKSPACE.bazel

OpenSSL: Update from 1.1.1q to 1.1.1t

---

.github/workflows/next.yml
.github/workflows/shared.yml
MAINTAINERS.md

ci: support `next/kelvin/*` binary and version string uploads

---

pkg/vere/io/ames.c
pkg/vere/pier.c

and makes a small fix intended for #305.

vere: decrements arvo kelvin compat

---

pkg/noun/jets/e/base.c
pkg/noun/jets/e/scot.c
pkg/noun/jets/e/scow.c
pkg/noun/jets/q.h
pkg/noun/jets/tree.c
pkg/noun/jets_tests.c
pkg/noun/serial.c
pkg/noun/serial.h

This PR is a straight port of urbit/urbit#6008 to this new repo. Details and benchmarks are in the old PR.

u3: adds jets for printing unsigned auras

---

pkg/vere/io/ames.c

We were incrementing the queue size counter conditionally, only for packets we want to forward. But for all packets, we were issuing a scry, and the callback would unconditionally decrement the queue size counter, leading to underflows. That, in turn, would result in vere thinking the queue was full when it wasn't.
Here, we make the least invasive change that resolves that particular bug. There may or may not still be other things wrong with the logic/factoring around the packet queue and lane scries.
f9e8542f9 changed the factoring here, making normal packet sending and forwarding take the same code path. ~~But also, even before that change, we were always sending the head of the packet queue to whatever lane scry result we got, which feels like it might not be right, _especially given …

ames: minimum viable decrement underflow hotfix

---

README.md

readme: add newline to run ci

---

pkg/vere/io/http.c

Haven't tested this, pushing early to get feedback on the approach. Basically, we put `[~ ~]` scries into the cache just like any other noun, and if `_http_cache_respond` sees `[~ ~]`, it falls back to `_http_req_dispatch`.
Resolves https://github.com/urbit/urbit/issues/6582

http: fallback to Eyre on failed cache scry

---

pkg/vere/main.c

add --no-demand to --help

---

pkg/noun/events.c

This PR is the simplest available fix for #451.

u3: enforce a max of one page in south.bin

---

pkg/noun/jets/d/by_bif.c
pkg/noun/jets/d/by_dif.c

Companion PR to [#6639 in Arvo](https://github.com/urbit/urbit/pull/6639)

jets: match hoon changes to bif:by

---

pkg/vere/main.c

Fixes #482. This looks like a bad cherry-pick on my part, porting old code.

meld: once is enough

---

pkg/vere/io/conn.c

conn: stop crashing on small receiving buffers

---

pkg/noun/jets/c/dor.c
pkg/noun/jets/c/mor.c

Fix advisory types in dor/mor jets.

---

pkg/vere/io/ames.c

Fix typo in ames.c

---

.github/workflows/docker-shared.yml

build: fix docker workflow

---

pkg/vere/io/ames.c

DNS galaxy resolution needs to be treated differently when dealing with STUN packets to our sponsor and when this is meant to be for another galaxy, as part of sending an ames packet.

ames: independent galaxy dns resolution for stun

---

pkg/vere/io/ames.c

ames: fix galaxy domain check

---

pkg/vere/main.c

vere: add --serf-bin option to provide path to serf

---

pkg/vere/main.c

Revert "vere: add --serf-bin option to provide path to serf"

---

pkg/vere/io/ames.c

Improves printing of galaxy DNS resolution for both ames and stun messages

ames: fix ames czar prints

---

BUILD.bazel

We got access to macstadium so we can now put this in as mentioned in #588 .

Revert "Revert "build: recent macOS updates clang""

---

pkg/noun/manage.c
pkg/vere/main.c

Same as #613 but for the `release` branch.

vere: adds --gc-early flag to pack and meld subcommands

---

pkg/vere/io/behn.c
pkg/vere/main.c
pkg/vere/vere.h

This problem is very tedious to work around without a way to keep running even without timers.

vere: add flag to continue running after behn: queue blocked

---

pkg/vere/main.c

building on #663, improving #654.

vere: respect --loom in subprocess replay

---

pkg/vere/io/ames.c

ames: only print packet drop-count on drop

---

pkg/vere/dawn.c
pkg/vere/king.c
pkg/vere/pier.c
pkg/vere/vere.h

Resolves https://github.com/urbit/urbit/issues/7013

Double boot protection

---

pkg/noun/allocate.c
pkg/noun/allocate.h
pkg/noun/jets.c
pkg/noun/jets.h
pkg/noun/manage.c
pkg/noun/manage.h
pkg/noun/nock.c
pkg/noun/nock.h
pkg/noun/vortex.c
pkg/noun/vortex.h
pkg/vere/king.c
pkg/vere/serf.c
pkg/vere/serf.h

Posting a bit of cleanup here rather than just submitting comments on the PR.

mass: improvements

---

pkg/noun/manage.c

Hotfix of outdated URL hardcoded into binary.

Update notice about swap space URL.

---

pkg/noun/events.c

#622 helped with this, but it's still overly laconic about what's going on. I think this is better.

events: even better error messages for partial write

---

pkg/vere/io/http.c

[UIP-0120 HTTP Streaming](https://github.com/urbit/UIPs/blob/main/UIPS/UIP-0120.md)
Resolves [#urbit/urbit7014](https://github.com/urbit/urbit/issues/7014)
requires eyre changes from https://github.com/urbit/urbit/pull/7033
and clay gang changes from https://github.com/urbit/urbit/pull/7038

http: streaming

---

CONTRIBUTING.md

Since I can never remember these and derive them _ab initio_ every single time.

Add debugging instructions

---

.github/workflows/docker-shared.yml

ci: fix typo in `docker-shared.yml`

---

ext/gmp/gen/README.md

Resolves https://github.com/urbit/vere/pull/733#issuecomment-2406342185

docs: add configure opts to gmp readme

---

pkg/vere/io/mesa.c

My changing of the semantics of the request bitset in #754 messed with the congestion control. This PR restores the outstanding fragments in flight tracking by using a counter, getting 30 mb/s with this for pokes on a M2 max locally.

mesa: track outstanding request fragments for congestion control

---

pkg/vere/io/behn.c

vere: don't double free egg

---

pkg/vere/io/mesa.c

These fixes combine to fix a rare segfault in the scenario when an arvo retry arrives when a request is already outstanding.

mesa: do not insert new request if old still pending

---

pkg/vere/io/ames.c
pkg/vere/io/mesa.c
pkg/vere/io/mesa/pact.c

The commit messages have the details.

mesa: more fixes

---

build.zig.zon
ext/avahi/build.zig.zon
ext/backtrace/build.zig.zon
ext/curl/build.zig.zon
ext/gmp/build.zig.zon
ext/h2o/build.zig.zon
ext/libuv/build.zig.zon
ext/lmdb/build.zig.zon
ext/murmur3/build.zig.zon
ext/natpmp/build.zig.zon
ext/openssl/build.zig.zon
ext/pdjson/build.zig.zon
ext/sigsegv/build.zig.zon
ext/softblas/build.zig.zon
ext/softfloat/build.zig.zon
ext/unwind/build.zig.zon
ext/urcrypt/build.zig.zon
ext/wasm3/build.zig.zon
ext/whereami/build.zig.zon
pkg/c3/build.zig.zon
pkg/noun/build.zig.zon
pkg/vere/build.zig.zon

Mostly resolves #816: zlib is still being refetched for some reason.

zig: new hash format

---

pkg/noun/jets/136/tree.c

Jet registration for `+vi` door https://github.com/urbit/urbit/pull/7162

+vi registration

---

pkg/past/migrate.h
pkg/past/migrate_v2.c
pkg/past/migrate_v3.c
pkg/past/migrate_v4.c
pkg/past/migrate_v5.c
pkg/vere/disk.c

adds more safety checks (and better errors) to pier migrations

---

pkg/noun/palloc.c

allocator errors: assert sanity or bail:meme

---

pkg/noun/palloc.c

u3: correct ASan poison annotations in |pack
